# Generated by Django 2.0.2 on 2018-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
                ('credits', models.CharField(max_length=2)),
                ('taught_semester', models.CharField(max_length=1)),
                ('module_type', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ucas_code', models.CharField(max_length=10)),
                ('modules', models.ManyToManyField(to='builder.Module')),
            ],
        ),
    ]
