# Generated by Django 2.0.2 on 2018-02-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='taught_semester',
            field=models.CharField(choices=[(1, '1'), (2, '2')], default='1', max_length=1),
        ),
    ]
