# Generated by Django 2.0.2 on 2018-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20180224_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(related_name='_module_prerequisites_+', to='builder.Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='taught_semester',
            field=models.CharField(max_length=1),
        ),
    ]
