# Generated by Django 2.0.2 on 2018-02-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20180224_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='modules',
            field=models.ManyToManyField(related_name='programmes', to='builder.Module'),
        ),
    ]
