# Generated by Django 2.0.2 on 2018-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20180224_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(related_name='is_prerequisite_of', to='builder.Module'),
        ),
    ]
