# Generated by Django 2.0.2 on 2018-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_auto_20180224_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='years',
            field=models.CharField(default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='criteria',
            field=models.ManyToManyField(related_name='accreditations', to='builder.Criterion'),
        ),
    ]
