# Generated by Django 2.0.2 on 2018-02-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_auto_20180225_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('C', 'Compulsory'), ('O', 'Optional'), ('D', 'Discovery')], default='C', max_length=1),
        ),
    ]
