# Generated by Django 2.0.2 on 2018-02-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_auto_20180225_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'verbose_name_plural': 'Criteria'},
        ),
    ]
