# Generated by Django 2.0.2 on 2018-03-08 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0009_auto_20180226_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='programmes',
            field=models.ManyToManyField(related_name='is_accredited_by', to='builder.Programme'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='is_met_by',
            field=models.ManyToManyField(related_name='meets', to='builder.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='manager',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programme',
            name='level',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(default='10', max_length=15),
        ),
    ]
