# Generated by Django 2.0.2 on 2018-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_auto_20180308_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='module',
            name='credits',
            field=models.CharField(default='10', max_length=2),
        ),
        migrations.AlterField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='is_prerequisite_of', to='builder.Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='taught_semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('1 & 2', '1 & 2')], default=('1', '1'), max_length=5),
        ),
    ]
