# Generated by Django 2.0.2 on 2018-03-26 06:53

from django.db import migrations, models
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_auto_20180313_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditation',
            name='programmes',
        ),
        migrations.AddField(
            model_name='accreditation',
            name='abbreviation',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='programme',
            name='accreditations',
            field=models.ManyToManyField(related_name='programmes', to='builder.Accreditation'),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, limit_choices_to=django.db.models.query_utils.Q(('level', '1'), ('level', '2'), _connector='OR'), related_name='is_prerequisite_of', to='builder.Module'),
        ),
    ]
